version: "3.0"
services:
  api:
    image: tubes-2-wbd-rest:latest
    ports:
      - 3000:3000
    hostname: rest-api-service
    env_file: .env
    volumes:
      - ./src:/usr/src/app/src
      - ./storage:/usr/src/app/storage
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - api-postgresql-redis
  postgresql:
    image: postgres:latest
    ports:
      - 5433:5432
    hostname: db-rest-api-service
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: always
    networks:
      - api-postgresql-redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - api-postgresql-redis
networks:
  api-postgresql-redis:
    driver: bridge
